
package com.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Wed Jan 24 11:27:48 IST 2018
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "message", namespace = "http://soap.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "message", namespace = "http://soap.com/")

public class Message {


}

